server:
  port: 8084
  error:
    include-message: always
    include-stacktrace: always
    whitelabel:
      enabled: true
spring:
  application:
    name: system
  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-date-timestamps-as-nanoseconds: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    modules-to-install: com.fasterxml.jackson.datatype.jsr310.JavaTimeModule
  datasource:
    url: jdbc:kingbase8://localhost:54321/course_manager?characterEncoding=UTF-8&useUnicode=true
    username: SYSTEM
    password: 123456
    driver-class-name: com.kingbase8.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      connection-test-query: SELECT 1
      validation-timeout: 5000
      pool-name: SystemHikariCP
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    user:
      name: admin
      password: admin123
  redis:
    host: localhost
    port: 6379
    database: 0

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: com.cemenghui.system.entity

jwt:
  secret: cemenghui-secret-key
  expiration: 86400000
  access-expire: 86400000
  refresh-expire: 604800000

minio:
  accessKey: minioadmin
  secretKey: minioadmin
  endpoint: http://localhost:9000
  bucket: system-files

mcp:
  server:
    url: http://127.0.0.1:6277
    auth-token: b78780b7f43d9d961b61bdc38227f01e2038491264231081120c505f6f90c8d8

dify:
  api-key: "your-dify-api-key"
  base-url: "https://api.dify.ai/v1"

app:
  jwt:
    secret: 2Qw1Q2hhdEdQVDQxLjFfU2FmZUtleUhlcmU2Nzg5MApQd2Vy
    expiration: 86400000
    refresh-expiration: 604800000
