server:
  port: 8081

spring:
  application:
    name: course
  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-date-timestamps-as-nanoseconds: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    modules-to-install: com.fasterxml.jackson.datatype.jsr310.JavaTimeModule
  datasource:
    url: jdbc:kingbase8://localhost:54321/course_manager?characterEncoding=UTF-8&useUnicode=true
    username: SYSTEM
    password: 123456
    driver-class-name: com.kingbase8.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      connection-test-query: SELECT 1
      validation-timeout: 5000
      pool-name: CourseHikariCP
  web:
    resources:
      static-locations: classpath:/static/,classpath:/public/,classpath:/resources/,classpath:/META-INF/resources/
  security:
    user:
      name: admin
      password: admin123
  redis:
    host: localhost
    port: 6379
    database: 0
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: com.cemenghui.course.entity

jwt:
  secret: cemenghui-secret-key
  expiration: 86400000

minio:
  accessKey: minioadmin
  secretKey: minioadmin
  endpoint: http://localhost:9000
  bucket: course-files

mcp:
  server:
    url: http://127.0.0.1:6277
    auth-token: b78780b7f43d9d961b61bdc38227f01e2038491264231081120c505f6f90c8d8

dify:
  api-key: "app-0aNJ1b5OVdl8fYZIW7f3K4WZ"
  base-url: "https://api.dify.ai/v1"
  workflow:
    url: http://localhost:8088/workflow/U7GxMeHuVNJC1Kd8
  api:
    key: app-Z4eFAVjcGNqXSDsJyP8ZA4bW
  # Dify 课程优化配置
  course:
    optimization:
      url: http://localhost:8088/workflow/6vZFPlP5pITAU8Qk
      key: app-sDs04lJf0Zp0sxQEoemW05M1

app:
  jwt:
    secret: your_jwt_secret_key_please_change
    expiration: 86400000
    refresh-expiration: 604800000