# 生产环境配置
server:
  port: 8080

spring:
  datasource:
    url: jdbc:kingbase8://localhost:54321/course_manager
    username: SYSTEM
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.kingbase8.Driver

  redis:
    host: localhost
    port: 6379
    password: ${REDIS_PASSWORD:}
    database: 0

logging:
  level:
    com.cemenghui: info
    org.springframework.security: warn
  file:
    name: logs/course-manager.log

# 生产环境多数据源配置 - 统一数据库
course:
  datasource:
    url: jdbc:kingbase8://localhost:54321/course_manager
    username: SYSTEM
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.kingbase8.Driver
  redis:
    database: 1

meeting:
  datasource:
    url: jdbc:kingbase8://localhost:54321/course_manager
    username: SYSTEM
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.kingbase8.Driver
  redis:
    database: 2

news:
  datasource:
    url: jdbc:kingbase8://localhost:54321/course_manager
    username: SYSTEM
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.kingbase8.Driver
  redis:
    database: 3