server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: course-manager

  # 数据源配置
  datasource:
    # 主数据源 - 统一数据库
    url: jdbc:kingbase8://localhost:54321/course_manager
    username: SYSTEM
    password: 123456
    driver-class-name: com.kingbase8.Driver

    # 连接池配置
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Redis配置
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

# MyBatis配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.cemenghui.*.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# JWT配置
jwt:
  secret: cemenghui-secret-key
  expiration: 86400000  # 24小时

# MinIO配置
minio:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucket:
    course: course-files
    meeting: meeting-files
    system: system-files

# 日志配置
logging:
  level:
    com.cemenghui: debug
    org.springframework.security: debug
  file:
    name: logs/course-manager.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 多数据源配置 - 统一数据库
course:
  datasource:
    url: jdbc:kingbase8://localhost:54321/course_manager
    username: SYSTEM
    password: 123456
    driver-class-name: com.kingbase8.Driver
  redis:
    database: 1

meeting:
  datasource:
    url: jdbc:kingbase8://localhost:54321/course_manager
    username: SYSTEM
    password: 123456
    driver-class-name: com.kingbase8.Driver
  redis:
    database: 2

news:
  datasource:
    url: jdbc:kingbase8://localhost:54321/course_manager
    username: SYSTEM
    password: 123456
    driver-class-name: com.kingbase8.Driver
  redis:
    database: 3